### DISCUSSION TITLE
Sumo

### DISCUSSION THREAD

**Discussion by GoodestEnglish** [diamond-rip/Eden#66] [Kit creations]
```yml
kits:
  sumo:
    enabled: true
    ranked: true
    display-name: '&6Sumo'
    priority: 5
    damage-ticks: 19
    display-icon: |
      rO0ABXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFwdAAPTGph
      dmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFibGVNYXAk
      U2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAlsABGtleXN0ABNbTGphdmEvbGFuZy9PYmplY3Q7WwAG
      dmFsdWVzcQB+AAR4cHVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAAAAJ0AAI9
      PXQABHR5cGV1cQB+AAYAAAACdAAeb3JnLmJ1a2tpdC5pbnZlbnRvcnkuSXRlbVN0YWNrdAAFU1RJ
      Q0s=
    description: '["","\u00267Hit your enemy into the water!"]'
    potion-effects: ''
    armor-loadout: |
      rO0ABXcEAAAABHBwcHA=
    contents-loadout: |
      rO0ABXcEAAAAJHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcA==
    game-rules: '{"receiveKitLoadoutBook":false,"deathOnWater":true,"boxing":false,"bed":false,"breakGoal":false,"portalGoal":false,"projectileOnly":false,"hypixelUHC":false,"spleef":false,"healthRegeneration":true,"showHealth":false,"foodLevelChange":false,"point":false,"rankedPoint":true,"resetArenaWhenGetPoint":false,"build":false,"startFreeze":true,"noDamage":true,"instantGapple":false,"enderPearlCooldown":false,"clearBlock":false,"dropItemWhenDie":true,"noFallDamage":true,"giveBackArrow":false,"respawnTime":5,"maximumPoints":3,"newRoundTime":5,"knockbackName":"default"}'
    kit-match-types: '["SOLO","SPLIT","FFA"]'
    kit-extra-item: '[]'
```
