### ISSUE TITLE
Teams and Placeholders

### ISSUE THREAD

**Issue by Chromaah** [diamond-rip/Eden#445]
before you post the next official update, can you add suggestion 2 from the discussion tab list #355 ? i think i'd be cool to have a papi placeholder that displays this too, like %eden_player_team_color% for example, and %eden_player_team_letter%. 

oh also is there a placeholder that displays player status? like %eden_player_status% which returns 'PLAYING' if ingame, 'IN-QUEUE' if in queue and 'IN-LOBBY' if in lobby, etc.

tbh makes everything a lot cleaner, and adds more uses if you dont use integrated nametags

(i also want this so that i can make my server look seamless, since this is how it is in bedwars and other of my servers)

_Originally posted by @Chromaah in https://github.com/diamond-rip/Eden/issues/441#issuecomment-1633511359_

**Comment by GoodestEnglish** [comment]
Added

**Comment by Chromaah** [comment]
hey seems like you added the placeholders but not the actual team thing...
![image](https://github.com/diamond-rip/Eden/assets/123222872/cab8e501-978c-407e-916b-41189114eb7e)
for example this image^ insteaad of it being like that it should look like this:
![image](https://github.com/diamond-rip/Eden/assets/123222872/7610f03a-85ad-4bfd-98a0-b0773d88432c)
with red being red team, and blue being blue team. this looks sooo much better than the picture before this...

For example. the message when the player scores has their team color, so these death messages can too.

**Comment by Chromaah** [comment]
@GoodestEnglish

**Comment by GoodestEnglish** [comment]
Sorry I misunderstand it. Will work on it again

**Comment by Chromaah** [comment]
no pronlem, tyy :>

**Comment by GoodestEnglish** [comment]
Oppsie, missed this issues. Here's an upcoming update which adds the placeholders for your request.
[Eden-1.1.27-BETA-795c2d2-all.jar.zip](https://github.com/diamond-rip/Eden/files/12137385/Eden-1.1.27-BETA-795c2d2-all.jar.zip)


```yml
match:
  death-message:
    ## {0} - Entity relation color
    ## {2} - Entity team color
    disconnect: "{0}{1} &7disconnected."
    ## {0} - Entity relation color
    ## {2} - Killer relation color
    ## {4} - Entity team color
    ## {5} - Killer team color
    killed: "{2}{3} &7killed {0}{1}&7."
    ## {0} - Entity relation color
    ## {2} - Entity team color
    default: "{0}{1} &7died."
```
