### ISSUE TITLE
Small Suggestion - Arena's Menu

### ISSUE THREAD

**Issue by Chromaah** [diamond-rip/Eden#481]
~~----------------------------------------------------~~

This is just a small thing that bugs me but:
1. In the arenas menu (when executing /arena) I have multiple maps with the displayname 'Aquarium' for example, but they are for different modes. For example, I have a bridge map that is aquarium themed, but also a pvp map for BUHC, Gapple, etc. And in the arenas menu they just all appear as 'Aquarium' so i have to click on all of them until i find the right one to modify:
![image](https://github.com/diamond-rip/Eden/assets/123222872/83b1c63f-4d1b-425b-9242-62406ba64256)

- I would like it to be like the kit menu where it shows kit display name but kit identifier next to it:
![image](https://github.com/diamond-rip/Eden/assets/123222872/0b4a48bc-befb-41c1-a61d-4bd6c5c6810d)

- So it should look like 'Aquarium (aquariumbridge)'

~~----------------------------------------------------~~

**Comment by Miab0** [comment]
It already exists, it was added in #103 so you probably didn't update your language.yml
Check that it is in the updated format:
```
  menu:
    title: "Arenas Preview"
    arena-edit:
      name: "&b&l{0} &7({1})"
      lore:
        - ""
        - "&e&nClick to edit arena settings!"
```
